// Constants
const thumbnailPath = "/img/thumbnail/MelanjutkanTonton/";
const commonCategories = ["Misteri", "Kriminal", "Fantasi"];
const commonStyle = "box";
const totalEpisodes = 14;

const resumeMovies = [
    {
        style: commonStyle,
        type: "movie",
        title: "Don't Look Up",
        image: `${thumbnailPath}tn1.png`,
        rating: "4.5/5",
        eps: "Episode 1",
        duration: 153,
        progress: "40%",
        totaleps: totalEpisodes,
        category: commonCategories,
        label: null,
        neweps: false,
        top10: false,
    },
    {
        style: commonStyle,
        type: "series",
        title: "The Batman",
        image: `${thumbnailPath}tn2.png`,
        rating: "4.2/5",
        eps: "Episode 2",
        duration: 254,
        progress: "16%",
        totaleps: totalEpisodes,
        category: commonCategories,
        label: "new Episode",
        neweps: false,
        top10: true,
    },
    {
        style: commonStyle,
        type: "movie",
        title: "Blue Lock",
        image: `${thumbnailPath}tn3.png`,
        rating: "4.6/5",
        eps: "Episode 4",
        duration: 44,
        progress: "56%",
        totaleps: totalEpisodes,
        category: commonCategories,
        label: "Top 10",
        neweps: true,
        top10: false,
    },
    {
        style: commonStyle,
        type: "series",
        title: "A Man Called Otto",
        image: `${thumbnailPath}tn4.png`,
        rating: "4.3/5",
        eps: "Episode 3",
        duration: 54,
        progress: "18%",
        totaleps: totalEpisodes,
        category: commonCategories,
        label: null,
        neweps: false,
        top10: true,
    },
    {
        style: commonStyle,
        type: "movie",
        title: "A Man Called Otto",
        image: `${thumbnailPath}tn4.png`,
        rating: "4.3/5",
        eps: "Episode 5",
        duration: 145,
        progress: "100%",
        totaleps: totalEpisodes,
        category: commonCategories,
        label: null,
        neweps: false,
        top10: false,
    },
];

export default resumeMovies;
